<?php
/**
 * Created by PhpStorm.
 * User: vuquangthinh
 * Date: 5/31/2016
 * Time: 1:52 AM
 */
namespace quangthinh\yii\adminlte\widgets;

use quangthinh\yii\adminlte\ICheckAsset;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\widgets\InputWidget;

class ICheck extends InputWidget
{
    public $clientOptions = [
        'checkboxClass' => 'icheckbox_square-blue',
        'radioClass' => 'iradio_square-blue',
        'increaseArea' => '20%',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        ICheckAsset::register($this->view);
    }

    public function run()
    {
        $this->view->registerJs('$("#' . $this->options['id'] . '").iCheck(' . Json::encode($this->clientOptions) . ');');
        if ($this->model) {
            $this->options['label'] = null;
            return Html::activeCheckbox($this->model, $this->attribute, $this->options);
        }
        return Html::checkbox($this->name, $this->value, $this->options);
    }
}